### ISSUE TITLE
Unused branches

### ISSUE THREAD

**Issue by yosefHesham** [mwenyoa/Portfolio#11]
Hey @mwenyoa , its better to remove unused branches.

**Comment by mwenyoa** [comment]
Hi @yosefHesham, well noted!
I will try to remove them.

**Comment by mwenyoa** [comment]
Hey @yosefHesham thanks again for your feedback and observation, my working tree is clean now. 👍

**Comment by yosefHesham** [comment]
Any time mate 🤗

**Comment by yosefHesham** [comment]
Thanks my friend for taking this into account
